version: "3.7"

services:
  mysql:
    container_name: mysql
    build: docker/db
    env_file: docker/db/.env.local
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_local:/var/lib/mysql:delegated

  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    env_file: docker/golang/.env.local
    ports:
      - 8080:8080
    volumes:
      - ./internal/db/migrations/mysql/:/internal/db/migrations/mysql/
    depends_on:
      - mysql

volumes:
  db_local:


# 初回 up のときは、データベース初期化に時間がかかるので connection refusedになります
# 再度 docker-compose up してください

# docker-compose exec mysql bash でDBサーバー内に入れる