// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Class struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Day       int        `json:"day"`
	Period    int        `json:"period"`
	Color     string     `json:"color"`
	Style     string     `json:"style"`
	Teacher   string     `json:"teacher"`
	Credit    *int       `json:"credit"`
	Memo      *string    `json:"memo"`
	RoomOrURL string     `json:"roomOrUrl"`
	Timetable *Timetable `json:"timetable"`
}

type ClassTime struct {
	ID        string     `json:"id"`
	Period    int        `json:"period"`
	StartTime *string    `json:"startTime"`
	EndTime   *string    `json:"endTime"`
	Timetable *Timetable `json:"timetable"`
}

type DeleteUser struct {
	Password string `json:"password"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewClass struct {
	Name      string  `json:"name"`
	Day       int     `json:"day"`
	Period    int     `json:"period"`
	Style     *string `json:"style"`
	Teacher   *string `json:"teacher"`
	RoomOrURL *string `json:"roomOrUrl"`
}

type NewClassTime struct {
	Period    int     `json:"period"`
	StartTime *string `json:"startTime"`
	EndTime   *string `json:"endTime"`
}

type NewTimetable struct {
	Name    string `json:"name"`
	Days    int    `json:"days"`
	Periods int    `json:"periods"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
	School   string `json:"school"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Timetable struct {
	ID         string              `json:"id"`
	Name       string              `json:"name"`
	Days       int                 `json:"days"`
	Periods    int                 `json:"periods"`
	CreatedAt  string              `json:"createdAt"`
	UpdatedAt  string              `json:"updatedAt"`
	IsDefault  bool                `json:"isDefault"`
	Classes    []*Class            `json:"classes"`
	Classtimes []*ClassTime        `json:"classtimes"`
	RowData    []*TimetableRowData `json:"rowData"`
	User       *User               `json:"user"`
}

type TimetableRowData struct {
	Periods   int        `json:"periods"`
	Classes   []*Class   `json:"Classes"`
	StartTime string     `json:"startTime"`
	EndTime   string     `json:"endTime"`
	Timetable *Timetable `json:"timetable"`
}

type UpdateClass struct {
	Name      *string `json:"name"`
	Day       int     `json:"day"`
	Period    int     `json:"period"`
	Color     *string `json:"color"`
	Style     *string `json:"style"`
	Teacher   *string `json:"teacher"`
	Credit    *int    `json:"credit"`
	Memo      *string `json:"memo"`
	RoomOrURL *string `json:"roomOrUrl"`
}

type UpdateClassTime struct {
	Period    int     `json:"period"`
	StartTime *string `json:"startTime"`
	EndTime   *string `json:"endTime"`
}

type UpdateTimetable struct {
	Name      *string `json:"name"`
	Days      *int    `json:"days"`
	Periods   *int    `json:"periods"`
	IDDefault *bool   `json:"idDefault"`
}

type UpdateUser struct {
	Email           *string `json:"email"`
	Password        *string `json:"password"`
	School          *string `json:"school"`
	Name            *string `json:"name"`
	CurrentPassword *string `json:"currentPassword"`
}

type User struct {
	ID         string       `json:"id"`
	Email      string       `json:"email"`
	School     *string      `json:"school"`
	Name       *string      `json:"name"`
	Timetables []*Timetable `json:"timetables"`
}
